// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hljmozrnnizbnsfhxfvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhsam1venJubml6Ym5zZmh4ZnZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3MTM1NzksImV4cCI6MjA1MDI4OTU3OX0.S4OcY2MMWrauJGBWy3PRb7I6NEQv2t6Qf8lEAW-n-og";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);